name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: debian-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v3
    - name: Build Release Artifacts
      run: make release
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "releases/*.tar.gz,releases/*.zip"
        body: "This is a test release."



